linters-settings:
  errcheck:
    check-type-assertions: true
  forbidigo:
    forbid:
      - '^fmt\.Print'
      - '^log\.'
      - '^print$'
      - '^println$'
      - '^panic$'
  godox:
    # TODO, OPT, etc. comments are fine to commit. Use FIXME comments for
    # temporary hacks, and use godox to prevent committing them.
    keywords: [FIXME]
  varnamelen:
    ignore-decls:
      - T any
      - i int
      - wg sync.WaitGroup
linters:
  enable-all: true
  disable:
    - copyloopvar       # only valid for go v1.22 and above
    - cyclop            # covered by gocyclo
    - depguard          # unnecessary for small libraries
    - execinquery       # deprecated in golangci v1.58 
    - exhaustruct       # many exceptions
    - exportloopref     # deprecated in golangci v1.60.2
    - funlen            # rely on code review to limit function length
    - gochecknoglobals  # many exceptions
    - gocognit          # dubious "cognitive overhead" quantification
    - gofumpt           # prefer standard gofmt
    - goimports         # rely on gci instead
    - gomnd             # deprecated in golangci v1.58 in favor of mnd
    - mnd               # some unnamed constants are okay
    - intrange          # only valid for go v1.22 and above
    - ireturn           # "accept interfaces, return structs" isn't ironclad
    - lll               # don't want hard limits for line length
    - maintidx          # covered by gocyclo
    - nlreturn          # generous whitespace violates house style
    - testpackage       # internal tests are fine
    - thelper           # we want to print out the whole stack
    - wrapcheck         # don't _always_ need to wrap errors
    - wsl               # generous whitespace violates house style
issues:
  exclude-dirs-use-default: false
  exclude:
    # Don't ban use of fmt.Errorf to create new errors, but the remaining
    # checks from err113 are useful.
    - "do not define dynamic errors.*"
  exclude-rules:
    - linters:
      - nilnil
      path: compiler_version.go
    - linters:
      - protogetter
      path: protoplugin_test.go
    - linters:
      - protogetter
      path: validate.go
    - linters:
      - nestif
      path: validate.go
      # compatibility.go contains functions copied from the Golang source, do not
      # modify to make them in line with our lint standards.
    - linters:
        - forbidigo
        - varnamelen
      path: compatibility.go
    - linters:
        - dupl
        - forcetypeassert
      path: protopluginutil/source_retention_options_test.go
